AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 025351005176

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: bethel-m
      AccountId: '025351005176'
      RootEmail: bethelcletus87@gmail.com
      Alias: aws-bethel-users

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies: !Ref BlockCloudTrailConfigurationOptionsSCP

  CrcOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: CRC
      ServiceControlPolicies: !Ref AllowServicesToCrcSCP
      Accounts:
        - !Ref CrcAccount
        - !Ref DevelopmentAccount

  CrcAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: CRC
      AccountId: '914581014840'
      RootEmail: bethelcletus87+CRC@gmail.com

  DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: development
      AccountId: '248899349741'
      RootEmail: bethelcletus87+development@gmail.com

  BlockCloudTrailConfigurationOptionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: Block cloud trail configuration options
      Description: Deny access to modify cloud trail configurations
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'cloudtrail:AddTags'
              - 'cloudtrail:CreateTrail'
              - 'cloudtrail:DeleteTrail'
              - 'cloudtrail:RemoveTags'
              - 'cloudtrail:StartLogging'
              - 'cloudtrail:StopLogging'
              - 'cloudtrail:UpdateTrail'
            Resource:
              - '*'
        
  AllowServicesToCrcSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: Allow services to crc
      Description: a list of allowed services to crc
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Stmt1111111111111
            Effect: Allow
            Action:
              - 'ec2:*'
              - 'elasticloadbalancing:*'
              - 'codecommit:*'
              - 'cloudtrail:*'
              - 'codedeploy:*'
            Resource:
              - '*'
        

