name: Terraform ci/cd 
run-name: Deployment by @${{ github.actor }}
on:
  pull_request:
    types:
      - closed
    branches:
      - main
# add a build job, when you use hugo  
jobs:
  if_merged:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
    - name: install terraform 
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - run: terraform --version

    - name: checkout repository
      uses: actions/checkout@v3 
    - run: ls 
    - run: pwd 


