name: Terraform ci/cd 
run-name: Deployment by @${{ github.actor }}
on:
  pull_request:
    types:
      - closed
    branches:
      - main
 

env:
  AWS_REGION : "eu-west-2"
# add a build job, when you use hugo  
jobs:
  CRC-after-merged:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read
    steps:
    # - name: install terraform 
    #   uses: hashicorp/setup-terraform@v2
    #   with:
    #     terraform_version: 1.3.7
    # - run: |
    #     terraform --version
    # - name: configure aws credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: arn:aws:iam::745517959886:role/gha_role
    #     role-session-name: CRCsession
    #     role-duration-seconds: 900
    #     aws-region: ${{ env.AWS_REGION}}
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::745517959886:role/gha_role
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: eu-west-2

    - name: checkout repository
      uses: actions/checkout@v3 

    - name: terraform init 
      run: |
        cd iac/main
        terraform init 

    # - name: Terraform plan 
    #   env:
    #     TF_VAR_GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY}}
    #     TF_VAR_GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET}}
    #   run: | 
    #     cd iac/main
    #     echo "### Terraform plan" 
    #     terraform plan -no-color 
    #   continue-on-error: true

    # - name: Terraform apply
    #   env:
    #     TF_VAR_GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY}}
    #     TF_VAR_GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET}}
    #   run: | 
    #     cd iac/main
    #     echo "### Terraform plan" 
    #     terraform apply -auto-approve -input=false
    #   continue-on-error: true

    # - name: Invalidate CloudFront
    #   uses: chetan/invalidate-cloudfront-action@v2
    #   env:
    #     DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
    #     PATHS: "/*"
    #     AWS_REGION: "eu-west-2"

    - name: Terraform destroy
      env:
        TF_VAR_GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY}}
        TF_VAR_GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET}}
      run: | 
        cd iac/main
        terraform destroy -auto-approve
      continue-on-error: true