name: Terraform ci/cd 
run-name: Deployment by @${{ github.actor }}
on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  AWS_REGION : "eu-west-2"
# add a build job, when you use hugo  
jobs:
  if_merged:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
    - name: install terraform 
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - run: |
        terraform --version

    # - name: configure aws credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: arn:aws:iam::745517959886:role/gha_role
    #     role-session-name: CRCsession
    #     role-duration-seconds: 900
    #     aws-region: ${{ env.AWS_REGION}}
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::745517959886:role/gha_role
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: eu-west-2

    - name: checkout repository
      uses: actions/checkout@v3 

    - name: terraform init 
      run: |
        cd iac/main
        ls 
        terraform init 

    - name: Terraform plan 
      run: | 
        echo "### Terraform plan" >> >$GITHUB_STEP_SUMMARY
        terraform plan -no-color >>$GITHUB_STEP_SUMMARY