name: Terraform ci/cd 
run-name: Deployment by @${{ github.actor }}
on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  AWS_REGION : "eu-west-2"
# add a build job, when you use hugo  
jobs:
  if_merged:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
    - name: install terraform 
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - run: terraform --version

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${seccret.AWS_ROLE_ARN}
        role-session-name: CRCsession
        aws-region: ${{ env.AWS_REGION}}

    - name: checkout repository
      uses: actions/checkout@v3 

    - name: terraform init 
      run: |
        cd iac/main
        ls 
        terraform init 

    - name: Terraform plan 
      run: | 
        echo "### Terraform plan" >> >$GITHUB_STEP_SUMMARY
        terraform plan -no-color >>$GITHUB_STEP_SUMMARY